name: Build APK Release

on:
  push:
    branches:
      - main  # Change to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '4.2.2'  # Update to the Flutter version you want
          channel: 'stable'  # You can also specify the channel if needed

      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release
